services:
  tesla-fullscreen:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tesla_fullscreen_app
    ports:
      - "5050:5000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
